/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThinkspacesRouteImport } from './routes/thinkspaces'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewQueueRouteImport } from './routes/review-queue'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThinkspacesIndexRouteImport } from './routes/thinkspaces.index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as ReviewQueueIndexRouteImport } from './routes/review-queue.index'
import { Route as ThinkspacesThinkspaceIdRouteImport } from './routes/thinkspaces.$thinkspaceId'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsProductRouteImport } from './routes/settings.product'
import { Route as ThinkspacesCreateDraftThinkspaceIdRouteImport } from './routes/thinkspaces.create.$draftThinkspaceId'

const ThinkspacesRoute = ThinkspacesRouteImport.update({
  id: '/thinkspaces',
  path: '/thinkspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewQueueRoute = ReviewQueueRouteImport.update({
  id: '/review-queue',
  path: '/review-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThinkspacesIndexRoute = ThinkspacesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ThinkspacesRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const ReviewQueueIndexRoute = ReviewQueueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReviewQueueRoute,
} as any)
const ThinkspacesThinkspaceIdRoute = ThinkspacesThinkspaceIdRouteImport.update({
  id: '/$thinkspaceId',
  path: '/$thinkspaceId',
  getParentRoute: () => ThinkspacesRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProductRoute = SettingsProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => SettingsRoute,
} as any)
const ThinkspacesCreateDraftThinkspaceIdRoute =
  ThinkspacesCreateDraftThinkspaceIdRouteImport.update({
    id: '/create/$draftThinkspaceId',
    path: '/create/$draftThinkspaceId',
    getParentRoute: () => ThinkspacesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/review-queue': typeof ReviewQueueRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/thinkspaces': typeof ThinkspacesRouteWithChildren
  '/settings/product': typeof SettingsProductRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/thinkspaces/$thinkspaceId': typeof ThinkspacesThinkspaceIdRoute
  '/review-queue/': typeof ReviewQueueIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/thinkspaces/': typeof ThinkspacesIndexRoute
  '/thinkspaces/create/$draftThinkspaceId': typeof ThinkspacesCreateDraftThinkspaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings/product': typeof SettingsProductRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/thinkspaces/$thinkspaceId': typeof ThinkspacesThinkspaceIdRoute
  '/review-queue': typeof ReviewQueueIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/thinkspaces': typeof ThinkspacesIndexRoute
  '/thinkspaces/create/$draftThinkspaceId': typeof ThinkspacesCreateDraftThinkspaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/review-queue': typeof ReviewQueueRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/thinkspaces': typeof ThinkspacesRouteWithChildren
  '/settings/product': typeof SettingsProductRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/thinkspaces/$thinkspaceId': typeof ThinkspacesThinkspaceIdRoute
  '/review-queue/': typeof ReviewQueueIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/thinkspaces/': typeof ThinkspacesIndexRoute
  '/thinkspaces/create/$draftThinkspaceId': typeof ThinkspacesCreateDraftThinkspaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/review-queue'
    | '/settings'
    | '/thinkspaces'
    | '/settings/product'
    | '/settings/profile'
    | '/thinkspaces/$thinkspaceId'
    | '/review-queue/'
    | '/settings/'
    | '/thinkspaces/'
    | '/thinkspaces/create/$draftThinkspaceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings/product'
    | '/settings/profile'
    | '/thinkspaces/$thinkspaceId'
    | '/review-queue'
    | '/settings'
    | '/thinkspaces'
    | '/thinkspaces/create/$draftThinkspaceId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/review-queue'
    | '/settings'
    | '/thinkspaces'
    | '/settings/product'
    | '/settings/profile'
    | '/thinkspaces/$thinkspaceId'
    | '/review-queue/'
    | '/settings/'
    | '/thinkspaces/'
    | '/thinkspaces/create/$draftThinkspaceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ReviewQueueRoute: typeof ReviewQueueRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  ThinkspacesRoute: typeof ThinkspacesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thinkspaces': {
      id: '/thinkspaces'
      path: '/thinkspaces'
      fullPath: '/thinkspaces'
      preLoaderRoute: typeof ThinkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-queue': {
      id: '/review-queue'
      path: '/review-queue'
      fullPath: '/review-queue'
      preLoaderRoute: typeof ReviewQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thinkspaces/': {
      id: '/thinkspaces/'
      path: '/'
      fullPath: '/thinkspaces/'
      preLoaderRoute: typeof ThinkspacesIndexRouteImport
      parentRoute: typeof ThinkspacesRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/review-queue/': {
      id: '/review-queue/'
      path: '/'
      fullPath: '/review-queue/'
      preLoaderRoute: typeof ReviewQueueIndexRouteImport
      parentRoute: typeof ReviewQueueRoute
    }
    '/thinkspaces/$thinkspaceId': {
      id: '/thinkspaces/$thinkspaceId'
      path: '/$thinkspaceId'
      fullPath: '/thinkspaces/$thinkspaceId'
      preLoaderRoute: typeof ThinkspacesThinkspaceIdRouteImport
      parentRoute: typeof ThinkspacesRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/product': {
      id: '/settings/product'
      path: '/product'
      fullPath: '/settings/product'
      preLoaderRoute: typeof SettingsProductRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/thinkspaces/create/$draftThinkspaceId': {
      id: '/thinkspaces/create/$draftThinkspaceId'
      path: '/create/$draftThinkspaceId'
      fullPath: '/thinkspaces/create/$draftThinkspaceId'
      preLoaderRoute: typeof ThinkspacesCreateDraftThinkspaceIdRouteImport
      parentRoute: typeof ThinkspacesRoute
    }
  }
}

interface ReviewQueueRouteChildren {
  ReviewQueueIndexRoute: typeof ReviewQueueIndexRoute
}

const ReviewQueueRouteChildren: ReviewQueueRouteChildren = {
  ReviewQueueIndexRoute: ReviewQueueIndexRoute,
}

const ReviewQueueRouteWithChildren = ReviewQueueRoute._addFileChildren(
  ReviewQueueRouteChildren,
)

interface SettingsRouteChildren {
  SettingsProductRoute: typeof SettingsProductRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsProductRoute: SettingsProductRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface ThinkspacesRouteChildren {
  ThinkspacesThinkspaceIdRoute: typeof ThinkspacesThinkspaceIdRoute
  ThinkspacesIndexRoute: typeof ThinkspacesIndexRoute
  ThinkspacesCreateDraftThinkspaceIdRoute: typeof ThinkspacesCreateDraftThinkspaceIdRoute
}

const ThinkspacesRouteChildren: ThinkspacesRouteChildren = {
  ThinkspacesThinkspaceIdRoute: ThinkspacesThinkspaceIdRoute,
  ThinkspacesIndexRoute: ThinkspacesIndexRoute,
  ThinkspacesCreateDraftThinkspaceIdRoute:
    ThinkspacesCreateDraftThinkspaceIdRoute,
}

const ThinkspacesRouteWithChildren = ThinkspacesRoute._addFileChildren(
  ThinkspacesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ReviewQueueRoute: ReviewQueueRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  ThinkspacesRoute: ThinkspacesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
