/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ThinkspacesRouteImport } from "./routes/thinkspaces";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ThinkspacesIndexRouteImport } from "./routes/thinkspaces.index";
import { Route as ThinkspacesThinkspaceIdRouteImport } from "./routes/thinkspaces.$thinkspaceId";

const ThinkspacesRoute = ThinkspacesRouteImport.update({
	id: "/thinkspaces",
	path: "/thinkspaces",
	getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
	id: "/login",
	path: "/login",
	getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => rootRouteImport,
} as any);
const ThinkspacesIndexRoute = ThinkspacesIndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => ThinkspacesRoute,
} as any);
const ThinkspacesThinkspaceIdRoute = ThinkspacesThinkspaceIdRouteImport.update({
	id: "/$thinkspaceId",
	path: "/$thinkspaceId",
	getParentRoute: () => ThinkspacesRoute,
} as any);

export interface FileRoutesByFullPath {
	"/": typeof IndexRoute;
	"/login": typeof LoginRoute;
	"/thinkspaces": typeof ThinkspacesRouteWithChildren;
	"/thinkspaces/$thinkspaceId": typeof ThinkspacesThinkspaceIdRoute;
	"/thinkspaces/": typeof ThinkspacesIndexRoute;
}
export interface FileRoutesByTo {
	"/": typeof IndexRoute;
	"/login": typeof LoginRoute;
	"/thinkspaces/$thinkspaceId": typeof ThinkspacesThinkspaceIdRoute;
	"/thinkspaces": typeof ThinkspacesIndexRoute;
}
export interface FileRoutesById {
	__root__: typeof rootRouteImport;
	"/": typeof IndexRoute;
	"/login": typeof LoginRoute;
	"/thinkspaces": typeof ThinkspacesRouteWithChildren;
	"/thinkspaces/$thinkspaceId": typeof ThinkspacesThinkspaceIdRoute;
	"/thinkspaces/": typeof ThinkspacesIndexRoute;
}
export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths: "/" | "/login" | "/thinkspaces" | "/thinkspaces/$thinkspaceId" | "/thinkspaces/";
	fileRoutesByTo: FileRoutesByTo;
	to: "/" | "/login" | "/thinkspaces/$thinkspaceId" | "/thinkspaces";
	id: "__root__" | "/" | "/login" | "/thinkspaces" | "/thinkspaces/$thinkspaceId" | "/thinkspaces/";
	fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute;
	LoginRoute: typeof LoginRoute;
	ThinkspacesRoute: typeof ThinkspacesRouteWithChildren;
}

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/thinkspaces": {
			id: "/thinkspaces";
			path: "/thinkspaces";
			fullPath: "/thinkspaces";
			preLoaderRoute: typeof ThinkspacesRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/login": {
			id: "/login";
			path: "/login";
			fullPath: "/login";
			preLoaderRoute: typeof LoginRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/thinkspaces/": {
			id: "/thinkspaces/";
			path: "/";
			fullPath: "/thinkspaces/";
			preLoaderRoute: typeof ThinkspacesIndexRouteImport;
			parentRoute: typeof ThinkspacesRoute;
		};
		"/thinkspaces/$thinkspaceId": {
			id: "/thinkspaces/$thinkspaceId";
			path: "/$thinkspaceId";
			fullPath: "/thinkspaces/$thinkspaceId";
			preLoaderRoute: typeof ThinkspacesThinkspaceIdRouteImport;
			parentRoute: typeof ThinkspacesRoute;
		};
	}
}

interface ThinkspacesRouteChildren {
	ThinkspacesThinkspaceIdRoute: typeof ThinkspacesThinkspaceIdRoute;
	ThinkspacesIndexRoute: typeof ThinkspacesIndexRoute;
}

const ThinkspacesRouteChildren: ThinkspacesRouteChildren = {
	ThinkspacesThinkspaceIdRoute: ThinkspacesThinkspaceIdRoute,
	ThinkspacesIndexRoute: ThinkspacesIndexRoute,
};

const ThinkspacesRouteWithChildren = ThinkspacesRoute._addFileChildren(ThinkspacesRouteChildren);

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	LoginRoute: LoginRoute,
	ThinkspacesRoute: ThinkspacesRouteWithChildren,
};
export const routeTree = rootRouteImport
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
	interface Register {
		ssr: true;
		router: Awaited<ReturnType<typeof getRouter>>;
	}
}
